/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Week2;
import java.util.Scanner;
import java.util.Random;

/**
 *
 * @author Acer
 */
public class T1Q12 {
    
    //11. Guess a random number generated by computer.
    
    public static void main(String[] args) {
        
        System.out.println("Guess a number from 1 to 10");
        Scanner sc = new Scanner(System.in);
        int num;
        num = sc.nextInt();
        
        Random rand = new Random();
        
        int randomNum = rand.nextInt(10) + 1;
        
        System.out.print("Generated number: " + randomNum);
        
        if (num == randomNum){
            System.out.println("\nYou guessed right!");}
        
        else {System.out.println("\nYou guessed wrong!");
        }
        
    }
}
