/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Week2;
import java.util.Random;
import java.util.Arrays;

/**
 *
 * @author Acer
 */
public class T1Q6 {
    
    public static void main(String[] args) {
        
        //Print the minimum number from 10 random numbers generated by computer.
        
        int n = 10;
        int[] randArray = new int[n];
        Random rand = new Random();
        for (int i = 0; i < n; i++)
        {randArray[i] = rand.nextInt(100);}
        
        Arrays.sort(randArray);
        System.out.println(Arrays.toString(randArray));
        
    }
    
}
