/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Week2;
import java.util.Random;
import java.util.Arrays;

/**
 *
 * @author Acer
 */
public class T1Q7 {
    
    public static void main(String[] args) {
        
        //Print the number of odd and even number from 10 random numbers generated by computer. 
        //The random number must be from 10 – 100.
        
        int n = 10;
        int[] randArray = new int[n];
        Random rand = new Random();
        
        for (int i = 0; i < n; i++)
            
            {   int min= 10; int max = 100;
                randArray[i] = rand.nextInt(max - min + 1) + min;}
            
            int evencounter = 0;
            int oddcounter = 0;
            
        for (int i = 0; i < n; i++)   
            if (randArray[i] %2 == 0)
                {evencounter++;}
            else {oddcounter++;
            }
        
            
        System.out.println(Arrays.toString(randArray));
        System.out.printf("Even: " + evencounter);
        System.out.printf("\nOdd: " + oddcounter);}}
      
        
    
    

